# Generated by Django 2.2.7 on 2019-11-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disabledperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PUMA', models.IntegerField()),
                ('ST', models.IntegerField()),
                ('AGEP', models.IntegerField()),
                ('SEX', models.IntegerField(choices=[('MALE', '1'), ('FEMALE', '2')])),
            ],
        ),
    ]
